### ISSUE TITLE
I'm not a coder, can't get to work?

### ISSUE THREAD

**Issue by aolivep** [MinusGix/MangarockDownloader#10]
Could exact instructions be provided? I'm not sure where exactly to put everything and etc so I'm having difficulties and it hasn't worked so far. Thanks either way, apologies beforehand

**Comment by MinusGix** [comment]
I'ts more useful if you can provide what issue you're having, and the OS. Also note that I'm not sure if this script works anymore (I think it should), but it has been almost a year since I wrote it, so they may have changed things (which might break my script).  
Step 1: Download nodejs. https://nodejs.org/ and install it .This is how my code is ran.  
Step 2: In the corner of the github file-info-area-thing there's a colored button which says "Download or Clone" click it, then click "Download Zip:.  
Step 3: Extract the zip file into a folder somewhere (Create a folder on the Desktop, or perhaps in your Documents folder)  .
Step 4: I don't know what system you're on, but if you're on Windows, then open explorer in the folder you created. 
Step 5: Create a new folder in that folder called `output` this is where
Step 5: Then Shift+Right-Click in the blank-area (where there is no files, so basically the blank area where files would appear), you should hopefully see an options that says something like: "Open CMD", "Open Command Prompt", "Open Powershell" or something like that.  
Step 5: You should hopefully have a black (command prompt) or blue (powershell) window open and now you should type `npm install` This installs all the code that my code requires (which lets it connect to the site and download the files in an easier way for me to code).  
Step 6: If there was no errors, then type `node downloader.js 5555555` or `node downloader.js mrs-serie-5555555` replacing the 5's with the id of the manga you want to download (I think you can see it in the url).  
Step 7: Wait. It should hopefully start downloading, and depending on how fast your net, and how many pages there are it can take a long time. You can stop it before it's done by pressing Ctrl+C in the window (or just by pressing the x.). The files will be put into `output/NameOfManga/` and then you can view them with an image viewer.

**Comment by MinusGix** [comment]
If you have an issue in doing this, then try to provide the info about it. (Ex: if you get an error doing `npm install` then post the log here, either as text or a screenshot)

**Comment by aolivep** [comment]
thanks for your help so far! I am running into issues I believe, heres my log so far. Again, I'm not proficient with code so I might just be missing something here. Thanks for your help!

PS C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Node.js\MangarockDownloader-master> npm install
npm WARN mangarock-downloader@1.0.0 No repository field.

audited 5 packages in 0.583s
found 0 vulnerabilities

PS C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Node.js\MangarockDownloader-master> node downloader.js 66020
Story id: mrs-serie-66020
(node:24792) UnhandledPromiseRejectionWarning: Error: Input must be string
    at sanitize (C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Node.js\MangarockDownloader-master\node_modules\sanitize-filename\index.js:41:11)
    at module.exports (C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Node.js\MangarockDownloader-master\node_modules\sanitize-filename\index.js:54:16)
    at Promise (C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Node.js\MangarockDownloader-master\smallMangaRock.js:55:26)
    at new Promise (<anonymous>)
    at getData.then.data (C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Node.js\MangarockDownloader-master\smallMangaRock.js:54:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:24792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MinusGix** [comment]
Hm, looks like the server complains about invalid requests. I'll try fixing this, but don't know how well I'll do since I don't really have the time to figure out how their api works again. (So if it's an easy modification I'll do it, if it's a more complicated one it may not happen soon :/)

**Comment by MinusGix** [comment]
Sigh, it looks like they've changed how their api works quite a bit, so I'd have to spend several hours figuring out how it works now (and it's more complicated than before) and that's probably not going to happen anytime soon. Sorry.
The manga you were trying to download is also on mangadex (a better manga site) https://mangadex.org/title/13871/dungeon-meshi/chapters/ and there's http://sizer99.com/pmd/ which should let you download it. (I haven't used it before, but it looks good).

**Comment by aolivep** [comment]
Alright, thank you for your effort!

Ah, I know! I was actually looking to download it since the MangaRock source seems to have the official translation for some reason, while other sources don't? I feel bad saying this, but I'm actually looking to download it so I can print and colour one of the title pages, since I'm an artist, and wanted the highest quality of the specific title page I could find, but I'll just use a screenshot from the app I suppose. It is possible to find the offical english online, but I can only seem to find them on odd suspicious download sites that demand you register, and I'd rather pass, haha.

Thank you so much for your effort, though! It's much appreciated. I hope the rest of the year goes well for you. Have a good one!

**Comment by MinusGix** [comment]
I can manually download one page from mangarock if you want, since that's not too hard.
